### ISSUE TITLE
Update needed: nutsdb updated

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-store#11]
- CB-Store version: Thu Feb 6 10:33:15 2020 +0900
```
commit 183d4e691c9f82227ca2f32a59405ffc2fa44513 (HEAD -> master, origin/master, origin/HEAD)
Merge: 199fcad cd85997
Author: ByoungSeob Kim <46367962+powerkimhub@users.noreply.github.com>
Date:   Thu Feb 6 10:33:15 2020 +0900

    Merge pull request #9 from jihoon-seo/200206-remove-go-mod-file
    
    Remove go.mod file
```

- To reproduce the error:
`source setup.env`
`cd test`
`go run test.go`

- Occurred error:
```
# github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver
/root/go/src/github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver/nutsdb-driver.go:170:38: assignment mismatch: 2 variables but 3 values
/root/go/src/github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver/nutsdb-driver.go:170:54: not enough arguments in call to tx.PrefixScan
        have (string, []byte, number)
        want (string, []byte, int, int)
```

- Reason:
"[Add Offset Search to PrefixScan() and PrefixSearchScan()](https://github.com/xujiajun/nutsdb/commit/dbe1b8a1bbb168c980f4466216334646b076bc83)" (Commits on Feb 21, 2020)
(FYI: https://github.com/xujiajun/nutsdb/commits/master )

- Diff of the function `PrefixScan()` in nutsdb:
https://github.com/xujiajun/nutsdb/commit/dbe1b8a1bbb168c980f4466216334646b076bc83#diff-86f9bd75d85012863d71ba827967dfa7

**Comment by jihoon-seo** [comment]
Temporary solution:
`cd ~/go/src/github.com/xujiajun/nutsdb`
`git reset --hard 2478252`

then do what you want;
e.g.
`cd ~/go/src/github.com/cloud-barista/cb-tumblebug/src`
`make`

**Comment by powerkimhub** [comment]
- 최신 nutsdb 인터페이스로 반영 
ref) https://github.com/cloud-barista/cb-store/pull/15

**Comment by powerkimhub** [comment]
- 2020.03.24. 이전 CB-Store 사용시: nutsdb 예전 버전 필요
  - old nutsdb 사용 설치 방법: https://github.com/cloud-barista/cb-store/issues/11#issuecomment-594281426

- 최신(2020.03.24 이후) CB-Store 사용시: 최신 nutsdb 설치
  - $go get -u github.com/xujiajun/nutsdb

**Comment by jihoon-seo** [comment]
지금 (2020-05-19) 와서 생각해 보니

nutsdb 개발자가
마지막 release 인 v0.5.0 을 릴리즈한 날짜는 2019년 11월 28일 이었고
그 이후로 간간히 commit 을 올리고 있습니다.

아직 v0.6.0 을 찍지 않았는데
제가 v0.5.0 릴리즈 이후의 latest 버전을 이용하여 CB 시리즈 빌드를 하려다 보니
문제가 생긴 것이었습니다.

nutsdb 에 v0.6.0 태그가 찍히기 전까지
저희가 택할 수 있는 옵션이 2가지 있습니다.

1. nutsdb 의 2020년 2월 21일자 변경에 대해
CB-Store 에서 대응 완료하였으므로
이대로 쭉 간다. (선호됨)
2. nutsdb 의 마지막 (stable?) 릴리즈가 v0.5.0 이므로
nustdb v0.5.0 사용하는 것으로 변경하고
이에 맞춰 CB-Store 에 적용했던 변경사항도 롤백한다. (선호되지 않음)
