### ISSUE TITLE
I wonder if there was a design intention about returning KeyValue.

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cb-store#40]
@powerkimhub (cc. @seokho-son)

CB-Tumblebug에서는 cb-store와 sqlite를 활용해 메타데이터/데이터를 운영 및 관리하고 있는데요.

이후 CB-Tumblebug에서 메타데이터/데이터 저장소의 개선을 계획하고 있습니다. 관련하여 cb-store에 한 가지 궁금한 사항이 있어 문의드립니다(유용한 디자인 패턴을 살리고자 문의드리는 사항입니다).

아래 Get(), GetList()의 리턴 타입이 `String` 형태의 Value 대신, `KeyValue` 객체를 리턴하도록 되어 있던데요. 디자인 상에서 어떤 의도가 있으셨는지 궁금합니다. 

https://github.com/cloud-barista/cb-store/blob/5e7c866c9fee5ae7703a4cc3678f24262938d21d/store-drivers/etcd-driver/etcd-driver.go#L113-L166

**Comment by powerkimhub** [comment]
@yunkon-kim (@seokho-son 

<br>

**[GetList]**
- GetList는 입력 Key를 포함하는 모든 KeyValue를 제공하므로, Key 값이 다른 Key:Value 목록을 제공합니다.
- 사용자는 제공 받은 결과에서 `실제 Key를 확인`할 수 있고, 각 Key의 Value를 조회할 수 있습니다.
- ex) https://github.com/cloud-barista/cb-store/blob/master/test/listall-test.go

**[Get]**
- Get은 exact match이어서 사용자가 반환 받은 Value에 대한 Key를 이미 정확하게 알고 있지만, 
- Get으로 얻은 값이 상위 호출한 함수에서 사용되거나 또는 다른 곳으로 전달과 전달이 되었을 때
  - 결과가 String 타입이면: cb-store 사용자가 Key를 계속 전달하고, 유지해야함
  - 결과가 KeyValue 타입이면: Key 전달이 불필요하고, Key든 Value든 값이 사용자가 필요한 경우 활용 가능

**Comment by yunkon-kim** [comment]
@powerkimhub 

(KV store에서 값을 얻은 이후) KeyValue가 여러 부분에서 활용되는 측면까지 고려하신 설계로 이해하였습니다. 설명해주셔서 감사합니다.
