### ISSUE TITLE
Suggestion: "/root/" -> "~/"

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-store#5]
https://github.com/cloud-barista/cb-store/blob/master/conf/store_conf.yaml

As-is:
`  dbpath: "/root/go/src/github.com/cloud-barista/cb-store/meta_db/dat"`

To-be:
`  dbpath: "~/go/src/github.com/cloud-barista/cb-store/meta_db/dat"`

Not tested yet.
Test is required.

**Comment by powerkimhub** [comment]
Good suggestion. I did it.
Thanks~
